### ISSUE TITLE
OpenTX 2.3.4 compability issues

### ISSUE THREAD

**Issue by syrekszymon** [flyduino/kissfc-tx-lua-scripts#43]
On OpenTX 2.3.4 LUA script can't save any parameters besides D Setpoint value. Same script on OpenTX 2.2.* works fine.

**Comment by lichtl** [comment]
Can you provide some more details? Which transmitter (Taranis, Xlite, Horus, T16 etc.) and which protocol (crossfire or sport)

**Comment by syrekszymon** [comment]
Taranis X9D+ OpenTX 2.3.4, TBS Crossfire Lite, fw 3.23, TBS Unify EVO fw 1.14, Fettec F7 FC fw 1.3RC40o, protocol CRSF, LUA v0.14.  I can see PID's, rates, etc. but can't save changes.
Same setup, only change OpenTX 2.2.* and LUA works fine.

![Adnotacja 2019-12-29 201942](https://user-images.githubusercontent.com/20756749/71561552-8ab85600-2a78-11ea-8d77-0bfc7d0ecb52.jpg)

**Comment by lichtl** [comment]
you can find the fixed files on my PR. Have to complete testing with real HW on T16/Xlite
