### ISSUE TITLE
Lua Scripts changes parameters (unintentionally)

### ISSUE THREAD

**Issue by N4V1G4T0R** [flyduino/kissfc-tx-lua-scripts#47]
Lua kiss-128x64-lua-scripts-1.0.0.zip
TX X-Lite Pro with OpenTX 2.3.7
FC Fettech KISS with most recent KISS firmware (updated 4/24/2020)

When changing PIDs via LUA (skipt) the PIDs change, but also some other settings eg. Filter, Yaw Filter Value, Min V, Max A. Copter does not arm after settings PIDs via LUA (because auf invalid settings)

**Comment by lichtl** [comment]
does this happen every time or just sometimes? The LUA uses only the change command for PIDs (which shouldn't change other settings).

**Comment by N4V1G4T0R** [comment]
It happened every time.

**Comment by lichtl** [comment]
could you provide a video and the exact firmware version and some more setup details (what receiver is being used CRSF/Frsky + which version/protocol). Since changing PID's command is not able to change other settings.

**Comment by N4V1G4T0R** [comment]
In the fast evolving world of drones, this is already past. The copter is still quite the same, but the transmitter firmware and SD Card were updated, in the meantime. I tried to reproduce the behavior, but no "success". It definitely is a new file for the KiSSCF, but I believe it's actually the same version. However, I moved on.
