### ISSUE TITLE
Holding "+" button doesn't auto incement value

### ISSUE THREAD

**Issue by slackista** [flyduino/kissfc-tx-lua-scripts#48]
In any page :
To increase value from 25 -> 200 you need to push "+" 175 times. Holding do nothing.
"-" is working fine - fast auto decreasing works.

Tested on CRSF with latest opentx https://github.com/opentx/opentx/commit/a4d6002178944cfe9e20535ecf80e0c4339f4694

**Comment by Freakshowdevil** [comment]
In "/src/common/KissUI.lua#L323"
`elseif event == EVT_VIRTUAL_INC_REP then`
Should it not be
`elseif event == EVT_VIRTUAL_INC_REPT then`

**Comment by lichtl** [comment]
fixed in 1.0.1
