### ISSUE TITLE
LUA Script syntax error

### ISSUE THREAD

**Issue by joker8656** [flyduino/kissfc-tx-lua-scripts#52]
Error as follows,

"Script Syntax error
loadscript("/kiss/pids.lua", "bt") error
File not found"

Im running "kiss-212x64-lua-scripts-1.0.1.zip" on my X9D+ copied to the telemetry folder.
open TX 2.3.9
KISS FC V2F7-1.3-RC45y 
XF Micro/nano 3.78

I've formatted and replaced all files with correct LUA scripts and the folder and file PIDS.lua is present so i'm unsure as to why that error is occurring. 

Thanks,

**Comment by fedorcomander** [comment]
move scripts to kiss folder in the root of sd card. 

---
Cheers,
Alex

**Comment by joker8656** [comment]
OK great thanks, they load up now but i get a "no telemetry" flashing at the bottom of the screen?

**Comment by fedorcomander** [comment]
thats something else. do u have telemetry from kiss? rediscover sensors and check all coming through.

**Comment by joker8656** [comment]
ok dumb answer but i was using the KISSSP lua instead of the Kiss CF lua. My bad . but you did help with the first part. THANKYOU

**Comment by fedorcomander** [comment]
dumb answer? ok. 

---
Cheers,
Alex

**Comment by joker8656** [comment]
Yeah sorry i mean. it was a simple answer/ solution, me being stupid not using the right script lol. Thanks again.
